name: Docker
on:
  schedule:
    # twice a month
    - cron: '20 15 5,20 * *'
  workflow_dispatch:

permissions:
  artifact-metadata: write
  attestations: write
  id-token: write
  packages: write

jobs:
  testbed-master:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: testbed-master
      target: testbed-master
  testbed-caddy:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: testbed-caddy
      target: testbed-caddy
